name: Checks
on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  eslint:
    name: Typescript build & ESlint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: NPM setup
        uses: actions/setup-node@v2
        with:
          version: 20

      - name: Environnement setup
        run: npm install

      - name: Typescript and Eslint scanning
        run: npm run lint
